package com.dynatrace.profilediff.ui;

import java.io.IOException;
import java.util.Arrays;

import javax.xml.stream.XMLStreamException;

import org.junit.Before;
import org.junit.Test;

import com.dynatrace.profilediff.XmlUtil;
import com.dynatrace.profilediff.ui.TwoWayModel.ChangeItem;

public class TwoWayModelFilterAttrChangeTest extends ModelTest_GEH_SystemProfile_Base {
	
	@Before
	public void before() throws XMLStreamException, IOException {
		boolean showParentPeers = false;
		// that's only present on the left side:
		XmlUtil.filter(xmlRight, "hybris", showParentPeers);
		XmlUtil.filter(xmlLeft, "hybris", showParentPeers);
	}

	@Test
	public void changes() throws XMLStreamException, IOException {
		ChangeItem item = ChangeItem.changes;
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "    measures"
				, "    configurations"
				, "      configuration:Default"
				, "        sensorconfig:hybris accelerator"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            (+) property"
				, "        sensorconfig:hybris webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            (+) property"
				), item, xmlRight);
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "    measures"
				), item, xmlLeft);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				), 8, item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				), 4, item, xmlLeft);
	}
	
	@Test
	public void structural() throws XMLStreamException, IOException {
		ChangeItem item = ChangeItem.structural;
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    measures"
				, "    configurations"
				, "      configuration:Default"
				, "        sensorconfig:hybris accelerator"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            (+) property"
				, "        sensorconfig:hybris webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            (+) property"
				), item, xmlRight);
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    measures"
				), item, xmlLeft);
		
		checkCollectChangedElements(Arrays.asList(
				  "(+) property"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				), 4, item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				), 0, item, xmlLeft);
	}
	
	@Test
	public void attributes() throws XMLStreamException, IOException {
		ChangeItem item = ChangeItem.attributes;
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "    measures"
				), item, xmlRight);
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "    measures"
				), item, xmlLeft);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				), 4, item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				), 4, item, xmlLeft);
	}
	
	/*
	 * Interesting trivia - splitted case "normal" in right and left side to not exceed the 64K method limit.
	 */
	
	@Test
	public void normalRight() throws XMLStreamException, IOException {
		ChangeItem item = ChangeItem.normal;
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "            timer"
				, "            loglevel"
				, "              console"
				, "              file"
				, "            communication"
				, "            capabilities"
				, "              capabilities:jvmti"
				, "              capabilities:jvmpi"
				, "              capabilities:dotnet"
				, "              capabilities:jvmtiEventNotifications"
				, "            debugflags"
				, "            transactionsamplingconfig"
				, "        metricgroup"
				, "        sensorplacement"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "            timer"
				, "            loglevel"
				, "              console"
				, "              file"
				, "            communication"
				, "            capabilities"
				, "              capabilities:jvmti"
				, "              capabilities:jvmpi"
				, "              capabilities:dotnet"
				, "              capabilities:jvmtiEventNotifications"
				, "            debugflags"
				, "            transactionsamplingconfig"
				, "        sensorplacement"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "    sensorgroups"
				, "      sensorgroup"
				, "        sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          class"
				, "          class"
				, "      sensorgroup"
				, "        sensor:Sampling(Java)"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "    measures"
				, "      measure:Execution CPU Time hybris Order:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution CPU Time hybris Payment:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution CPU Time hybris Product:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution Time hybris Order:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Execution Time hybris Payment:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Execution Time hybris Product:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Invocation of DefaultOrderService.placeOrder:Methods:Invocation"
				, "      measure:[y] (e) order total price:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) order total tax:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) order volume:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) solr server query time:Methods:Time"
				, "      measure:[y] (f) account addAddress:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) account editAddress:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) category page:Methods:Invocation"
				, "        argument"
				, "        argument"
				, "      measure:[y] (f) checkout place order:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) invocation of submitOrder:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) place order:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (s) category code from method:Business Transaction Evaluation/Filter/Grouping Values:Argument Value"
				, "      measure:[y] (s) product code from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) product manufacturer from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) product name from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) search parameter Dx:Business Transaction Evaluation/Filter/Grouping Values:Parameter Value"
				, "        sourcegroup:hybris accelerator"
				, "      measure:[y] (s) search parameter Ntt:Business Transaction Evaluation/Filter/Grouping Values:Parameter Value"
				, "        sourcegroup:hybris accelerator"
				, "      measure:[y] (s) search text from method:Business Transaction Evaluation/Filter/Grouping Values:Argument Value"
				, "    configurations"
				, "      configuration:Default"
				, "        sensorconfig:hybris accelerator"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            property"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            property"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "            property"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "            property"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "        sensorconfig:hybris webserver"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            property"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            property"
				, "            property"
				, "            (+) property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "            property"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "            property"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				), item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				), 8, item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				), 4, item, xmlLeft);
	}
	
	@Test
	public void normalLeft() throws XMLStreamException, IOException {
		ChangeItem item = ChangeItem.normal;
		
		checkModel(Arrays.asList(
				  "dynatrace"
				, "  (#) systemprofile"
				, "    (#) agentgroups"
				, "      agentgroup:hybris accelerator"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_accelerator"
				, "            timer"
				, "            loglevel"
				, "              console"
				, "              file"
				, "            communication"
				, "            capabilities"
				, "              capabilities:jvmti"
				, "              capabilities:jvmpi"
				, "              capabilities:dotnet"
				, "              capabilities:jvmtiEventNotifications"
				, "            debugflags"
				, "            transactionsamplingconfig"
				, "        metricgroup"
				, "        sensorplacement"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "      agentgroup:hybris webserver"
				, "        agentmappings"
				, "          (#) agentmapping:hybris_webserver"
				, "            timer"
				, "            loglevel"
				, "              console"
				, "              file"
				, "            communication"
				, "            capabilities"
				, "              capabilities:jvmti"
				, "              capabilities:jvmpi"
				, "              capabilities:dotnet"
				, "              capabilities:jvmtiEventNotifications"
				, "            debugflags"
				, "            transactionsamplingconfig"
				, "        sensorplacement"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "    sensorgroups"
				, "      sensorgroup"
				, "        sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "          class"
				, "          class"
				, "      sensorgroup"
				, "        sensor:Sampling(Java)"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "            method"
				, "          class"
				, "    measures"
				, "      measure:Execution CPU Time hybris Order:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution CPU Time hybris Payment:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution CPU Time hybris Product:API Breakdown:Execution CPU Time"
				, "        color"
				, "      measure:Execution Time hybris Order:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Execution Time hybris Payment:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Execution Time hybris Product:API Breakdown:Execution Time"
				, "        color"
				, "      measure:Invocation of DefaultOrderService.placeOrder:Methods:Invocation"
				, "      measure:[y] (e) order total price:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) order total tax:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) order volume:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (e) solr server query time:Methods:Time"
				, "      measure:[y] (f) account addAddress:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) account editAddress:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) category page:Methods:Invocation"
				, "        argument"
				, "        argument"
				, "      measure:[y] (f) checkout place order:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) invocation of submitOrder:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (f) place order:Methods:Invocation"
				, "        argument"
				, "      measure:[y] (s) category code from method:Business Transaction Evaluation/Filter/Grouping Values:Argument Value"
				, "      measure:[y] (s) product code from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) product manufacturer from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) product name from method:Business Transaction Evaluation/Filter/Grouping Values:Return Value"
				, "      measure:[y] (s) search parameter Dx:Business Transaction Evaluation/Filter/Grouping Values:Parameter Value"
				, "        sourcegroup:hybris accelerator"
				, "      measure:[y] (s) search parameter Ntt:Business Transaction Evaluation/Filter/Grouping Values:Parameter Value"
				, "        sourcegroup:hybris accelerator"
				, "      measure:[y] (s) search text from method:Business Transaction Evaluation/Filter/Grouping Values:Argument Value"
				, "    configurations"
				, "      configuration:Default"
				, "        sensorconfig:hybris accelerator"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "            property"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "            property"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
				, "        sensorconfig:hybris webserver"
				, "          sensor:com.compuware.php.WordPress"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.adk"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.cics"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.adonet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.appdomaininitialization"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnet"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.aspnetex"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.component"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.disableinlining"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.heap"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.httptagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.logging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messaging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.messagingreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.mqseriesreceiveentrypoint"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.remoting"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.threadtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wcftagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.webservicetagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.winforms"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.dotnet.wpf"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.euem.webserver"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ims"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imsconnect"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.imscontrol"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.awt"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.classloader"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ctg"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.default"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.ejb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.exception"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.executor"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hadoop"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.hibernate"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.http"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.imssoapgatewaytagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jbossesbtagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jdbc"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jms"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmsreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmstagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jmx"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jndi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.jta"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.logger"
				, "            property"
				, "            property"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.memory"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseries"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.mqseriesreceiveentry"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.muletagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.cassandra.tagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.hbase"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.nosql.mongodb"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmi"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.rmitagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servlet"
				, "            property"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.servletEndUserTagging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.struts"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tests"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.threadstart"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibco"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.tibcotagging"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.webservice"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.java.xa"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.actioncapturing"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.addeventlistenerwrapper"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.angular"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.bandwidth"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.core"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.dojo"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.extjs"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.genericxhr"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.icefaces"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.jquery"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.mootools"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.navtiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.perceivedrendertime"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.prototype"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.resourcetiming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.streaming"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.thirdparty"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.timeout"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.js.websockets"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.curl"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.default"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.exception"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.logging"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.mysql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.oracle"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.pdo"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.phpunit"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.postgresql"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.php.server"
				, "            property"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.javascript"
				, "            property"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.network"
				, "            property"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              mimetype"
				, "              urlpatternconfiguration"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.ria.rendering"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.dotnet"
				, "          sensor:com.dynatrace.diagnostics.knowledgesensor.sampling.java"
				, "          sensor:com.dynatrace.diagnostics.sensorgroup.method.Java.27aa393b70e52"
			), item, xmlLeft);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				, "(+) property"
				), 8, item, xmlRight);
		
		checkCollectChangedElements(Arrays.asList(
				  "(#) systemprofile"
				, "(#) agentgroups"
				, "(#) agentmapping:hybris_accelerator"
				, "(#) agentmapping:hybris_webserver"
				), 4, item, xmlLeft);
	}
}
